### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by v1rt** [joemaddalone/ReactSublimeSnippets#1]
Hi Joe,

How do I use this in ST3?

Thanks!

**Comment by joemaddalone** [comment]
In Sublime find the "Browse Packages" menu item.  Inside of that directory there will be a "User" directory.  Save "ReactSnippets.sublime-package" to that folder.

**Comment by v1rt** [comment]
Thanks!

**Comment by btray77** [comment]
This should be in the "Readme.md"

**Comment by joemaddalone** [comment]
This is no longer needed, the snippets are available from the Sublime Package Control as _React & React Router Snippets_.
