### ISSUE TITLE
Convert spaces into tabs for all snippets

### ISSUE THREAD

**Issue by hovsater** [joemaddalone/ReactSublimeSnippets#2]
First of all, big ups for creating these snippets. I find them really usefully in my everyday coding. Thank you!

So, I've noticed that these snippets don't adhere to whatever indention settings I have present. They always enforce an indention of 2 spaces. We can actually fix this by converting spaces into tabs. If every snippet uses tabs for indention, Sublime Text will automatically apply the proper indention settings when used.

**Comment by hovsater** [comment]
@joemaddalone would you like me to take a stab this? I'd be happy to help if you're short on time. 😃

**Comment by joemaddalone** [comment]
@KevinSjoberg , feel free to give it a go.

Running `npm start` will generate a ST3 package you can drop into your packages to try out.

Obviously changes should be limited to multi-line snippets.  The few that there are will be in snippets/React.

**Comment by hovsater** [comment]
Well, I never got around to it. 🙂 I'll close it instead of just keeping it open.
